hosts:
  - host: google.com
    users:
      - root
      - admin
  - host: amazon.com
    users:
      - root
keys:
  - name: johndoe@gmail.com
    description: John Doe
    key: ssh-rsa XXXXXXXXX
  - name: janedoe@gmail.com
    description: Jane Doe
    key: ssh-rsa YYYYYYYYY