keys:
  john-doe: ssh-ed25519 XXXXXXXXX
  jane-doe: ssh-ed25519 YYYYYYYYY

groups:
  admin:
    - john-doe
  marketing:
    - jane-doe

hosts:
  - host: google.com
    users:
      root:
        groups:
          - admin
      other-ssh-user:
        groups:
          - marketing
        keys:
          - john-doe

  - host: amazon.com
    port: 42069
    users:
      root:
        groups:
          - admin
